moved git-cat to hubflow

diff --git a/bin/git-cat b/bin/git-cat
--- a/bin/git-cat
+++ b/bin/git-cat
@@ -1,1 +1,41 @@
-../gitflow/git-cat
+#!/bin/bash
+
+#/ NAME
+#/     git cat -- show a file at a specific revision
+#/
+#/ SYNOPSIS
+#/     git cat [commit] [file]
+
+# figure out the project root under which bin, lib live
+shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
+
+# load a meat library
+source "$shome/bin/_prime" "$@"
+
+# entry point
+function main {
+  local commit="$1"; shift
+  local file="$1"; shift
+
+  # from http://michaelgoerz.net/blog/2009/10/three-little-git-scripts/
+  git cat-file -p "$(git ls-tree "$commit" "$file" | awk '{print $3}')"
+}
+
+# parse the command-line
+parse_command_line "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+if [[ "$#" < 1 ]]; then
+  logger_fatal "missing commit"
+  display_help
+  exit 1
+fi
+
+if [[ "$#" < 2 ]]; then
+  logger_fatal "missing filename"
+  display_help
+  exit 1
+fi
+
+# pass arguments to entry point
+main "$@"
